teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 8.0
    # scale_linear_turbo:
      # x: 10.0
    
    axis_linear:
      y: 0
    scale_linear:
      y: 8.0
    # scale_linear_turbo:
      # y: 10.0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 50.0

    enable_button: 4  # L2 shoulder button
